# Basic workflow to help het started with Actions
name: Simple Manual Workflow - Infrastructure

# Controls when the Actions will run

on:
  # Allows to run workflow manually from Actions tab
  workflow_dispatch:
  
# Workflow made up of several jobs
jobs:

  DEV:
    # Type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Dev
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a script
        run: |
          echo "I am running a job in the Dev environment"
          
  QA:
    # Type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: QA
    #needs: DEV
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a script
        run: |
          echo "I am running a job in the QA environment"
          
  STAGING:
    # Type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Staging
    #needs: QA
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a script
        run: |
          echo "I am running a job in the Staging environment"
          
  PROD:
    # Type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Prod
    #needs: STAGING
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a script
        run: |
          echo "I am running a job in the Prod environment"
